# Site settings
title: Christopher Hinstorff
tagline: But you can call me Chris
author: 
  name: Christopher Hinstorff
  email: chris@chinstorff.com
  github: chinstorff
  twitter: chinstorff

description: "Christopher Hinstorff's personal website"
baseurl: ""
url: "http://chinstorff.com/"

# Build settings
markdown: kramdown
permalink: /:categories/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments


JB:
  # Comments
  comments:
    provider: disqus
    disqus:
      short_name: 'chinstorff'
      
  # Analytics
  analytics:
    provider: google
    google:
      tracking_id : 'UA-43949530-1'

  # Sharing
  provider: false

  # Other helpers
  pages_list :
    provider : "custom" 